name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Build for all architectures
      run: sudo apt install nodejs && sudo npm i -g minify-all-js && make build

    - name: Create docker image
      run: make docker
